package renderer

import chroma "github.com/alecthomas/chroma/v2"

// A copy of https://github.com/catppuccin/chroma, but without the background color.
var catpuccinFrappeNoBg = chroma.MustNewStyle(
	"catpuccin-frappe-without-bg",
	chroma.StyleEntries{
		chroma.Background:               "", // <- !
		chroma.CodeLine:                 "#c6d0f5",
		chroma.Error:                    "#e78284",
		chroma.Other:                    "#c6d0f5",
		chroma.LineTableTD:              "",
		chroma.LineTable:                "",
		chroma.LineHighlight:            "bg:#51576d",
		chroma.LineNumbersTable:         "#838ba7",
		chroma.LineNumbers:              "#838ba7",
		chroma.Keyword:                  "#ca9ee6",
		chroma.KeywordReserved:          "#ca9ee6",
		chroma.KeywordPseudo:            "#ca9ee6",
		chroma.KeywordConstant:          "#ef9f76",
		chroma.KeywordDeclaration:       "#e78284",
		chroma.KeywordNamespace:         "#81c8be",
		chroma.KeywordType:              "#e78284",
		chroma.Name:                     "#c6d0f5",
		chroma.NameClass:                "#e5c890",
		chroma.NameConstant:             "#e5c890",
		chroma.NameDecorator:            "bold #8caaee",
		chroma.NameEntity:               "#81c8be",
		chroma.NameException:            "#ef9f76",
		chroma.NameFunction:             "#8caaee",
		chroma.NameFunctionMagic:        "#8caaee",
		chroma.NameLabel:                "#99d1db",
		chroma.NameNamespace:            "#ef9f76",
		chroma.NameProperty:             "#ef9f76",
		chroma.NameTag:                  "#ca9ee6",
		chroma.NameVariable:             "#f2d5cf",
		chroma.NameVariableClass:        "#f2d5cf",
		chroma.NameVariableGlobal:       "#f2d5cf",
		chroma.NameVariableInstance:     "#f2d5cf",
		chroma.NameVariableMagic:        "#f2d5cf",
		chroma.NameAttribute:            "#8caaee",
		chroma.NameBuiltin:              "#99d1db",
		chroma.NameBuiltinPseudo:        "#99d1db",
		chroma.NameOther:                "#c6d0f5",
		chroma.Literal:                  "#c6d0f5",
		chroma.LiteralDate:              "#c6d0f5",
		chroma.LiteralString:            "#a6d189",
		chroma.LiteralStringChar:        "#a6d189",
		chroma.LiteralStringSingle:      "#a6d189",
		chroma.LiteralStringDouble:      "#a6d189",
		chroma.LiteralStringBacktick:    "#a6d189",
		chroma.LiteralStringOther:       "#a6d189",
		chroma.LiteralStringSymbol:      "#a6d189",
		chroma.LiteralStringInterpol:    "#a6d189",
		chroma.LiteralStringAffix:       "#e78284",
		chroma.LiteralStringDelimiter:   "#8caaee",
		chroma.LiteralStringEscape:      "#8caaee",
		chroma.LiteralStringRegex:       "#81c8be",
		chroma.LiteralStringDoc:         "#737994",
		chroma.LiteralStringHeredoc:     "#737994",
		chroma.LiteralNumber:            "#ef9f76",
		chroma.LiteralNumberBin:         "#ef9f76",
		chroma.LiteralNumberHex:         "#ef9f76",
		chroma.LiteralNumberInteger:     "#ef9f76",
		chroma.LiteralNumberFloat:       "#ef9f76",
		chroma.LiteralNumberIntegerLong: "#ef9f76",
		chroma.LiteralNumberOct:         "#ef9f76",
		chroma.Operator:                 "bold #99d1db",
		chroma.OperatorWord:             "bold #99d1db",
		chroma.Comment:                  "italic #737994",
		chroma.CommentSingle:            "italic #737994",
		chroma.CommentMultiline:         "italic #737994",
		chroma.CommentSpecial:           "italic #737994",
		chroma.CommentHashbang:          "italic #626880",
		chroma.CommentPreproc:           "italic #737994",
		chroma.CommentPreprocFile:       "bold #737994",
		chroma.Generic:                  "#c6d0f5",
		chroma.GenericInserted:          "bg:#414559 #a6d189",
		chroma.GenericDeleted:           "bg:#414559 #e78284",
		chroma.GenericEmph:              "italic #c6d0f5",
		chroma.GenericStrong:            "bold #c6d0f5",
		chroma.GenericUnderline:         "underline #c6d0f5",
		chroma.GenericHeading:           "bold #ef9f76",
		chroma.GenericSubheading:        "bold #ef9f76",
		chroma.GenericOutput:            "#c6d0f5",
		chroma.GenericPrompt:            "#c6d0f5",
		chroma.GenericError:             "#e78284",
		chroma.GenericTraceback:         "#e78284",
	},
)
